### ISSUE TITLE
flask tumblelog is not working 

### ISSUE THREAD

**Issue by vikashruhil** [rozza/flask-tumblelog#7]
Vikashs-MacBook-Air:tumblelog vikashruhil$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from tumblelog import app
  File "/Users/vikashruhil/Downloads/flask-tumblelog-master/tumblelog/__init__.py", line 18, in <module>
    register_blueprints(app)
  File "/Users/vikashruhil/Downloads/flask-tumblelog-master/tumblelog/__init__.py", line 13, in register_blueprints
    from tumblelog.views import posts
  File "/Users/vikashruhil/Downloads/flask-tumblelog-master/tumblelog/views.py", line 5, in <module>
    from tumblelog.models import Post, Comment
  File "/Users/vikashruhil/Downloads/flask-tumblelog-master/tumblelog/models.py", line 6, in <module>
    class Post(db.DynamicDocument):
  File "/usr/local/lib/python2.7/site-packages/mongoengine/base/metaclasses.py", line 361, in __new__
    meta['index_specs'] = new_class._build_index_specs(meta['indexes'])
  File "/usr/local/lib/python2.7/site-packages/mongoengine/base/document.py", line 722, in _build_index_specs
    unique_indices = cls._unique_with_indexes()
  File "/usr/local/lib/python2.7/site-packages/mongoengine/base/document.py", line 861, in _unique_with_indexes
    field.document_type != cls):
  File "/usr/local/lib/python2.7/site-packages/mongoengine/fields.py", line 563, in document_type
    self.document_type_obj = get_document(self.document_type_obj)
  File "/usr/local/lib/python2.7/site-packages/mongoengine/base/common.py", line 25, in get_document
    """.strip() % name)
mongoengine.errors.NotRegistered: `Comment` has not been registered in the document registry.
            Importing the document class automatically registers it, has it
            been imported?

**Comment by thinkerou** [comment]
Please move class `Comment` to class `Post` before. [link](http://stackoverflow.com/questions/29434854/error-in-tumblelog-application-development-using-flask-and-mongoengine)

**Comment by knaggita** [comment]
start with class comment followed by post(interchange their order)

**Comment by afizing** [comment]
I did that .. but still i am getting the same error. 

# import required modules.
import datetime
from flask import url_for
from tumbleblog import db


class Comment(db.EmbeddedDocumentField):
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    body = db.StringField(verbose_name="Comment", required=True)
    author = db.StringField(verbose_name="Name", max_length=255, required=True)


class Post(db.Document):
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    title = db.StringField(max_length=255, required=True)
    slug = db.StringField(max_length=255, required=True)
    body = db.StringField(required=True)
    comments = db.ListField(db.EmbeddedDocumentField('Comment'))

    def get_absolute_url(self):
        return url_for('post', kwargs={"slug": self.slug})

    def __unicode__(self):
        return self.title

    meta = {
        'allow_inheritance': True,
        'indexes': ['-created_at', 'slug'],
        'ordering': ['-created_at']
    }

**Comment by afizing** [comment]
I did that .. but unfortunately still getting the same error.
